USE UAT_CUST_RISK_SCORING;
DROP TABLE IF EXISTS dbo.riskRatingCashReg;
DROP INDEX IF EXISTS TRN_INDEX ON dbo.riskRatingCashReg;
DROP INDEX IF EXISTS CRM_ID_INDEX ON dbo.riskRatingCashReg;
DROP INDEX IF EXISTS ID_TIMESTAMP_INDEX ON dbo.riskRatingCashReg;
CREATE TABLE dbo.riskRatingCashReg (
    ID INT IDENTITY(1, 1),
    TRN NVARCHAR(80) NULL,
    Cash_Intensive_Flag VARCHAR(6) NULL,
    REG_REPORT_ONE VARCHAR(6) NULL,
    DATE_ADDED DATETIME NULL,
    DATE_MODIFIED DATETIME NULL,
    CRMID NVARCHAR(80) NULL,
    MODIFIED_DATE DATETIME NULL
);
CREATE INDEX TRN_INDEX ON dbo.riskRatingCashReg(TRN);
CREATE INDEX CRM_ID_INDEX ON dbo.riskRatingCashReg(CRMID);
CREATE INDEX ID_TIMESTAMP_INDEX on dbo.riskRatingCashReg(ID, MODIFIED_DATE);