USE UAT_CUST_RISK_SCORING;
DROP TABLE IF EXISTS dbo.riskRating;
DROP INDEX IF EXISTS TRN_INDEX ON dbo.riskRating;
DROP INDEX IF EXISTS CUST_ID_INDEX ON dbo.riskRating;
DROP INDEX IF EXISTS ID_TIMESTAMP_INDEX ON dbo.riskRating;
CREATE TABLE dbo.riskRating (
    ID INT IDENTITY(1, 1),
    TRN NVARCHAR(80) NULL,
    CUST_ID NVARCHAR(80) NULL,
    RISK_SCORE BIGINT NULL,
    RISK_CATEGORY NVARCHAR(44) NULL,
    DATE_OF_RISK_SCORE DATETIME NULL,
    EXPIRY_DATE_OF_RISK_SCORE DATETIME NULL,
    LOADED_DATE DATETIME NULL,
    MODIFIED_DATE DATETIME NOT NULL
);
CREATE INDEX TRN_INDEX ON dbo.riskRating (TRN);
CREATE INDEX CUST_ID_INDEX ON dbo.riskRating(CUST_ID);
CREATE INDEX ID_TIMESTAMP_INDEX on dbo.riskRating(ID, MODIFIED_DATE);